### ISSUE TITLE
Autosort Tagged Books no longer working since v23.06

### ISSUE THREAD

**Issue by Divinii** [BookStackApp/hacks#5]
When saving a Page there is now an error:
![image](https://github.com/BookStackApp/hacks/assets/37466196/5e3984dc-89a1-4db8-bb5d-db4d49944e75)

Removing Autosort function.php resolves this. Books are also not being sorted. Container STD-out does not provide any logs.

**Comment by ssddanbrown** [comment]
Hi @Divinii,
Support for hacks is limited as per [the readme](https://github.com/BookStackApp/hacks#support--issues) and as per the warning banner on our hack pages. Therefore I'm going to close this off but feel free to provide a PR to update the hack if you can find the issue.

**Comment by Divinii** [comment]
Hey,

yeah I totally understand! Just wanted to put it here so you are aware if interested. My PHP-fu is not strong enough I think. :)
